# Generated by Django 3.1.4 on 2021-02-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='data',
            field=models.CharField(max_length=30),
        ),
    ]
